@startuml

left to right direction
skinparam packageStyle rectangle

title Use Case Diagram

:User: as User

User -> (As a User, I want to upload files)
User -> (As a User, I want to remove files)
User -> (As a User, I want to view the chat history)
User -> (As a User, I want to delete a chat page)
User -> (As a User, I want to create a new chat page)
User -> (As a User, I want to ask a question and get an answer/n according to the files)

@enduml
