@startuml

title UC5: Remove a Chat Page


autonumber

actor "<<user(c4)>> \nUser" as user
participant "<<system(c4)>> \nnBanks_RAGSystem" as sys

activate user
user -> sys : Requests to remove a chat page
activate sys
sys --> user: Requests the user to confirm the removal
deactivate sys
user -> sys : Confirms the removal
activate sys
sys -> sys : Validates the request
sys --> user: Notifies the user of successful removal
deactivate sys
deactivate user

@enduml