@startuml

title UC7: Ask a Question and Get an Answer


autonumber

participant "<<system(c4)>> \nnBanks_RAGSystem" as sys
actor "<<user(c4)>> \nUser" as user

activate user
user -> sys : Asks a question
activate sys
sys --> user: Provides an answer
deactivate sys
deactivate user

@enduml

