@startuml

title UC7: Ask a Question and Get an Answer


autonumber

actor "<<user(c4)>> \nUser" as user
participant "<<system(c4)>> \nnBanks_RAGSystem_SPA" as sys
participant "<<container(c4)>> \nnBanks_RAGSystem_API" as api
participant "<<container(c4)>> \nnBanks_RAGSystem_AI" as ai
participant "<<container(c4)>> \nnBanks_RAGSystem_VectorDB" as db2

activate user
user -> sys : Requests to ask a question
activate sys
sys --> user: Requests the user to provide a question
deactivate sys
user -> sys : Provides a question
activate sys
sys -> api: HTTP POST ("ask")
activate api
api -> api: Validates the question
api -> ai: Relevant files and question
activate ai
ai -> db2: Retrieve relevant file chunks
activate db2
db2 --> ai: Returns the relevant file chunks
deactivate db2
ai -> ai: Process the question with the retrieved file chunks
ai -> ai: Generates an answer
ai --> api: Returns the answer
deactivate ai
api --> sys: Code 200 (OK)
deactivate api
sys --> user: Delivers the answer
deactivate sys
deactivate user

@enduml